# These are supported funding model platforms
github: Zajroid # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: Zajroid # Replace with a single Patreon username
open_collective: Zajroid # Replace with a single Open Collective username
ko_fi: Zajroid # Replace with a single Ko-fi username
tidelift: Zajroid/klaramando-blog # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: "klaramando-blog" # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: Zajroid # Replace with a single Liberapay username
issuehunt: Zajroid # Replace with a single IssueHunt username
otechie: Zajroid # Replace with a single Otechie username
custom: "https://Zajroid.github.io/klaramando-blog/" # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']